services:
  g2o_deps:
    image: g2o/deps:latest
    container_name: g2o_deps
    stdin_open: true
    tty: true
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: deps
    environment:
      DISPLAY: $DISPLAY

  g2o_dev:
    image: g2o/dev:latest
    container_name: g2o_dev
    volumes:
      - type: bind
        source: ../
        target: /home/workspace/g2o
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
    network_mode: host
    environment:
      DISPLAY: $DISPLAY
    extends:
      service: g2o_deps

  g2o:
    image: g2o:latest
    build:
      target: install
    container_name: g2o
    extends:
      service: g2o_deps
